### ISSUE TITLE
ImportError: Cannot import site module and its dependencies: No module named site

### ISSUE THREAD

**Issue by Hipapheralkus** [PortSwigger/turbo-intruder#1]
Hi,
I want to ask about an exception I get, and how can I fix it:
```
Starting attack...
Error launching attack - bad python?
ImportError: Cannot import site module and its dependencies: No module named site
Determine if the following attributes are correct:
  * sys.path: ['C:\\Users\\name\\AppData\\Local\\Temp\\2\\burp3469202481907241985.tmp\\Lib', '__classpath__', '__pyclasspath__/']
    This attribute might be including the wrong directories, such as from CPython
  * sys.prefix: C:\Users\name\AppData\Local\Temp\2\burp3469202481907241985.tmp
    This attribute is set by the system property python.home, although it can
    be often automatically determined by the location of the Jython jar file

You can use the -S option or python.import.site=false to not import the site module

	at org.python.core.Py.ImportError(Py.java:328)
	at org.python.core.Py.importSiteIfSelected(Py.java:1563)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:116)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:94)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:71)
	at burp.Fast_httpKt.evalJython(fast-http.kt:91)
	at burp.TurboIntruderFrame$actionPerformed$1$1$1.invoke(fast-http.kt:199)
	at burp.TurboIntruderFrame$actionPerformed$1$1$1.invoke(fast-http.kt:138)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

```
I tried sending request from Repeater to Turbo Intruder, running your default script (with path set for 'D:\5chars.txt') on 1 thread, Windows Server 2016, from Burp 1.7.37, Turbo Intruder from BappStore with Extender -> Options -> Python Environment -> location of standalone JAR set for "C:\jython2.7.1\jython.jar". Apart from that, in Windows CMD command "python" results in running Python 3.6.4. (but when I try "import site" it works). Same for "Python2" -> results in running Python 2.7.12, and "import site" works as well.

**Comment by Hipapheralkus** [comment]
works perfectly with release 1.0.1, thanks:)
