### ISSUE TITLE
can't import custom Python module

### ISSUE THREAD

**Issue by adrian-rt** [PortSwigger/turbo-intruder#106]
Hi James,

I've wrote a custom Python module with the purpose of importing it inside Turbo Intduder, but TI can't import it.

my script starts like this:

import subprocess
import mtrand

but the following expcetion gets logged:

`Starting attack...
There was an error executing your Python script. This is probably due to a flaw in your script, rather than a bug in Turbo Intruder :)
If you think it is a Turbo Intruder issue, try out this script: https://raw.githubusercontent.com/PortSwigger/turbo-intruder/master/resources/examples/debug.py
For your convenience, here's the full stack trace:
Traceback (most recent call last):
  File "<string>", line 7, in <module>
ImportError: No module named mtrand

	at org.python.core.Py.ImportError(Py.java:328)
	at org.python.core.imp.import_first(imp.java:877)
	at org.python.core.imp.import_module_level(imp.java:972)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importOne(imp.java:1081)
	at org.python.pycode._pyx3.f$0(<string>:49)
	at org.python.pycode._pyx3.call_function(<string>)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.core.Py.exec(Py.java:1430)
	at org.python.util.PythonInterpreter.exec(PythonInterpreter.java:267)
	at burp.Fast_httpKt.evalJython(fast-http.kt:155)
	at burp.TurboIntruderFrame$actionPerformed$1$4$1.invoke(fast-http.kt:411)
	at burp.TurboIntruderFrame$actionPerformed$1$4$1.invoke(fast-http.kt:218)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

`
if I run python3 and then "import mtrand"  my module works just fine.

Any idea what the issue might be? The custom module is installed in a standard python location. Thanks.

Thanks.

**Comment by adrian-rt** [comment]
ahhhh.........

it seems TI is using python 2.70 inside and my module is made for python 3.8.10.

What's the best way forward for this please? can you upgrade to 3.8 easily? Thanks!

**Comment by adrian-rt** [comment]
so, I've ported my python module from 3.8 to python 2.7 however turbo inruder still throws an exception  when I try to import it.

In python2.7 all works fine just like in python3.8

`adrian@adrian-XPS-15-9570:~/Downloads/tools/pyphp_rand/php_rand$ python2
Python 2.7.18 (default, Mar  8 2021, 13:02:45) 
[GCC 9.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mtrand
>>> 
`

**Comment by adrian-rt** [comment]
I've even set the path for loading python modules in Extender -> Options, it's set to /usr/local/lib/python2.7/dist-packages

Yes my custom module still isn't loaded.

thanks.

**Comment by adrian-rt** [comment]
Hi James,

Indeed, thanks for answering here as well. I'l be looking at that option and also at using: https://jyni.org/
