### ISSUE TITLE
turbo-intruder error

### ISSUE THREAD

**Issue by angel1374** [PortSwigger/turbo-intruder#115]
`Loaded Turbo Intruder v1.0.19
Starting attack...
There was an error executing your Python script. This is probably due to a flaw in your script, rather than a bug in Turbo Intruder :)
If you think it is a Turbo Intruder issue, try out this script: https://raw.githubusercontent.com/PortSwigger/turbo-intruder/master/resources/examples/debug.py
For your convenience, here's the full stack trace:
java.lang.IllegalArgumentException: Cannot create PyString with non-byte value
	at org.python.core.PyString.<init>(PyString.java:64)
	at org.python.core.PyString.<init>(PyString.java:70)
	at org.python.core.Py.newString(Py.java:641)
	at org.python.core.PySystemState.initRegistry(PySystemState.java:800)
	at org.python.core.PySystemState.doInitialize(PySystemState.java:1045)
	at org.python.core.PySystemState.initialize(PySystemState.java:974)
	at org.python.core.PySystemState.initialize(PySystemState.java:930)
	at org.python.core.PySystemState.initialize(PySystemState.java:925)
	at org.python.core.PySystemState.initialize(PySystemState.java:920)
	at org.python.core.PySystemState.initialize(PySystemState.java:916)
	at org.python.core.ThreadStateMapping.getThreadState(ThreadStateMapping.java:32)
	at org.python.core.Py.getThreadState(Py.java:1440)
	at org.python.core.Py.getThreadState(Py.java:1436)
	at org.python.core.Py.getSystemState(Py.java:1456)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:105)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:94)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:71)
	at burp.Fast_httpKt.evalJython(fast-http.kt:130)
	at burp.TurboIntruderFrame$actionPerformed$1$4$1.invoke(fast-http.kt:353)
	at burp.TurboIntruderFrame$actionPerformed$1$4$1.invoke(fast-http.kt:208)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

Starting attack...
There was an error executing your Python script. This is probably due to a flaw in your script, rather than a bug in Turbo Intruder :)
If you think it is a Turbo Intruder issue, try out this script: https://raw.githubusercontent.com/PortSwigger/turbo-intruder/master/resources/examples/debug.py
For your convenience, here's the full stack trace:
java.lang.NullPointerException
	at org.python.core.PyModule.module___init__(PyModule.java:64)
	at org.python.core.PyModule.<init>(PyModule.java:47)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:112)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:94)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:71)
	at burp.Fast_httpKt.evalJython(fast-http.kt:130)
	at burp.TurboIntruderFrame$actionPerformed$1$4$1.invoke(fast-http.kt:353)
	at burp.TurboIntruderFrame$actionPerformed$1$4$1.invoke(fast-http.kt:208)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

Starting attack...
There was an error executing your Python script. This is probably due to a flaw in your script, rather than a bug in Turbo Intruder :)
If you think it is a Turbo Intruder issue, try out this script: https://raw.githubusercontent.com/PortSwigger/turbo-intruder/master/resources/examples/debug.py
For your convenience, here's the full stack trace:
java.lang.NullPointerException
	at org.python.core.PyModule.module___init__(PyModule.java:64)
	at org.python.core.PyModule.<init>(PyModule.java:47)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:112)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:94)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:71)
	at burp.Fast_httpKt.evalJython(fast-http.kt:130)
	at burp.TurboIntruderFrame$actionPerformed$1$4$1.invoke(fast-http.kt:353)
	at burp.TurboIntruderFrame$actionPerformed$1$4$1.invoke(fast-http.kt:208)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

Starting attack...
There was an error executing your Python script. This is probably due to a flaw in your script, rather than a bug in Turbo Intruder :)
If you think it is a Turbo Intruder issue, try out this script: https://raw.githubusercontent.com/PortSwigger/turbo-intruder/master/resources/examples/debug.py
For your convenience, here's the full stack trace:
java.lang.NullPointerException
	at org.python.core.PyModule.module___init__(PyModule.java:64)
	at org.python.core.PyModule.<init>(PyModule.java:47)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:112)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:94)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:71)
	at burp.Fast_httpKt.evalJython(fast-http.kt:130)
	at burp.TurboIntruderFrame$actionPerformed$1$4$1.invoke(fast-http.kt:353)
	at burp.TurboIntruderFrame$actionPerformed$1$4$1.invoke(fast-http.kt:208)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

`
![图片](https://user-images.githubusercontent.com/71721281/196688433-3eaba715-d530-4c32-baaa-6c719f0c7198.png)

**Comment by angel1374** [comment]
My name is java in the win 11 system. The default of the python dual environment is java 11 java 8 1.8. The default is python 3.8 python 2 2.7. Use jython standalone 2.7.2.jar

**Comment by angel1374** [comment]
Win10 is normal, but Win11 reports these errors

**Comment by angel1374** [comment]
Thank you. I've found the reason. It's because the JAVA dual environment is not completely divided

**Comment by albinowax** [comment]
Thanks for the update

**Comment by destinypwd** [comment]
> Thank you. I've found the reason. It's because the JAVA dual environment is not completely divided

I also encountered this problem. How did you solve it,thinks

**Comment by albinowax** [comment]
@destinypwd I'd suggest trying the Burp exe installer which comes with Java built in.

**Comment by angel1374** [comment]
Check the Java environment, it is recommended that a version of the Java environment, multiple versions of the Java environment need to be fully independent. I because multiple JAVA version not completely errors caused by segmentation
