### ISSUE TITLE
debug error,why?

### ISSUE THREAD

**Issue by angel1374** [PortSwigger/turbo-intruder#116]
Starting attack...
There was an error executing your Python script. This is probably due to a flaw in your script, rather than a bug in Turbo Intruder :)
If you think it is a Turbo Intruder issue, try out this script: https://raw.githubusercontent.com/PortSwigger/turbo-intruder/master/resources/examples/debug.py
For your convenience, here's the full stack trace:
java.lang.NullPointerException
	at org.python.core.PyModule.module___init__(PyModule.java:64)
	at org.python.core.PyModule.<init>(PyModule.java:47)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:112)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:94)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:71)
	at burp.Fast_httpKt.evalJython(fast-http.kt:35)
	at burp.TurboIntruderFrame$actionPerformed$1$ToggleAttack$actionPerformed$1.invoke(fast-http.kt:326)
	at burp.TurboIntruderFrame$actionPerformed$1$ToggleAttack$actionPerformed$1.invoke(fast-http.kt:276)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
![图片](https://user-images.githubusercontent.com/71721281/199192921-787370b3-86cc-451b-ba48-9de8b86e47ea.png)
![图片](https://user-images.githubusercontent.com/71721281/199193006-de5a7c57-cedb-429d-9bcb-d65aca193a15.png)

**Comment by albinowax** [comment]
Please try https://raw.githubusercontent.com/PortSwigger/turbo-intruder/master/resources/examples/debug.py and follow the instructions in there
