### ISSUE TITLE
Turbu Intruder `java.net.SocketException: Connection reset`

### ISSUE THREAD

**Issue by hostfree23434** [PortSwigger/turbo-intruder#118]
Hi,
I use turbo-intruder-all.jar with cli
many times i get this error:
``
java.net.SocketException: Connection reset
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
        at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
        at java.base/sun.security.ssl.SSLSocketInputRecord.readFully(SSLSocketInputRecord.java:461)
        at java.base/sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(SSLSocketInputRecord.java:243)
        at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:181)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1509)
        at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1476)
        at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1065)
        at java.base/java.io.InputStream.read(InputStream.java:205)
        at burp.ThreadedRequestEngine.sendRequests(ThreadedRequestEngine.kt:334)
        at burp.ThreadedRequestEngine.access$sendRequests(ThreadedRequestEngine.kt:17)
        at burp.ThreadedRequestEngine$1.invoke(ThreadedRequestEngine.kt:50)
        at burp.ThreadedRequestEngine$1.invoke(ThreadedRequestEngine.kt:49)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
Ignoring error: java.net.SocketException: Connection reset
``

Is there a solution?

Regards.

**Comment by albinowax** [comment]
Try reducing requestsPerConnection and/or disabling pipelining.
