### ISSUE TITLE
There was an error executing your Python script. This is probably due to a flaw in your script, rather than a bug in Turbo Intruder :) If you think it is a Turbo Intruder issue, try out this script: https://raw.githubusercontent.com/PortSwigger/turbo-intruder/master/resources/examples/debug.py For your convenience, here's the full stack trace: java.lang.NullPointerException: Cannot read field "modules" because the return value of "org.python.core.Py.getSystemState()" is null

### ISSUE THREAD

**Issue by jingaoying** [PortSwigger/turbo-intruder#139]
Starting attack...
There was an error executing your Python script. This is probably due to a flaw in your script, rather than a bug in Turbo Intruder :)
If you think it is a Turbo Intruder issue, try out this script: https://raw.githubusercontent.com/PortSwigger/turbo-intruder/master/resources/examples/debug.py
For your convenience, here's the full stack trace:
java.lang.NullPointerException: Cannot read field "modules" because the return value of "org.python.core.Py.getSystemState()" is null
	at org.python.core.PyModule.module___init__(PyModule.java:64)
	at org.python.core.PyModule.<init>(PyModule.java:47)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:112)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:94)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:71)
	at burp.Fast_httpKt.evalJython(fast-http.kt:139)
	at burp.TurboIntruderFrame$actionPerformed$1$4$1.invoke(fast-http.kt:394)
	at burp.TurboIntruderFrame$actionPerformed$1$4$1.invoke(fast-http.kt:217)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

Starting attack...
There was an error executing your Python script. This is probably due to a flaw in your script, rather than a bug in Turbo Intruder :)
If you think it is a Turbo Intruder issue, try out this script: https://raw.githubusercontent.com/PortSwigger/turbo-intruder/master/resources/examples/debug.py
For your convenience, here's the full stack trace:
java.lang.NullPointerException: Cannot read field "modules" because the return value of "org.python.core.Py.getSystemState()" is null
	at org.python.core.PyModule.module___init__(PyModule.java:64)
	at org.python.core.PyModule.<init>(PyModule.java:47)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:112)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:94)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:71)
	at burp.Fast_httpKt.evalJython(fast-http.kt:139)
	at burp.TurboIntruderFrame$actionPerformed$1$4$1.invoke(fast-http.kt:394)
	at burp.TurboIntruderFrame$actionPerformed$1$4$1.invoke(fast-http.kt:217)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

**Comment by jingaoying** [comment]
help me！

**Comment by albinowax** [comment]
Refer to https://github.com/PortSwigger/turbo-intruder/issues/69
