### ISSUE TITLE
Command line "Read timed out" error

### ISSUE THREAD

**Issue by Kevin4562** [PortSwigger/turbo-intruder#142]
Hello, I am attempting to use Turbo Intruder from the CLI but am facing an error. I am on Windows, I have tried running the latest release version as well as building it from source. Intruder works fine inside of Burp just not from CLI.

**Command:**
`java -jar turbo.jar .\turbo_request.py .\request.txt https://example.net:443 foo`

**Error:**
```shell
java.net.SocketTimeoutException: Read timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:278)
        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:304)
        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:345)
        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:794)
        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1025)
        at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:483)
        at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:477)
        at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)
        at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1461)
        at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1066)
        at java.base/java.io.InputStream.read(InputStream.java:217)
        at burp.ThreadedRequestEngine.sendRequests(ThreadedRequestEngine.kt:303)
        at burp.ThreadedRequestEngine.access$sendRequests(ThreadedRequestEngine.kt:19)
        at burp.ThreadedRequestEngine$1.invoke(ThreadedRequestEngine.kt:54)
        at burp.ThreadedRequestEngine$1.invoke(ThreadedRequestEngine.kt:53)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
Ignoring error: java.net.SocketTimeoutException: Read timed out
null
Reqs: 0 | Queued: 1 | Duration: 14 | RPS: 0 | Connections: 2 | Retries: 0 | Fails: 1 | Next:  |
``` 

**turbo_requests.py:**
```python
# Use this to debug issues with Turbo Intruder connecting to sites
# If this script as-is fails, try changing Engine.THREADED to Engine.BURP
# If that makes it work, file a report on http://github.com/PortSwigger/turbo-intruder/issues
# Please include the target request/domain, and your OS and Java version from Help->Diagnostics
def queueRequests(target, wordlists):
    engine = RequestEngine(endpoint=target.endpoint,
                           concurrentConnections=1,
                           requestsPerConnection=1,
                           pipeline=False,
                           maxRetriesPerRequest=0,
                           engine=Engine.THREADED
                           )

    engine.queue(target.req)
    engine.queue(target.req)
    engine.queue(target.req)


def handleResponse(req, interesting):
    print(req.response)
``` 

**request.txt**
```
GET / HTTP/1.1
Host: example.net
Connection: keep-alive
```

**Comment by albinowax** [comment]
HTTP/1.1 header blocks are terminated with a blank line - you need to add a bank line on the end of request.txt
