### ISSUE TITLE
Error launching attack - bad python?

### ISSUE THREAD

**Issue by vipinbihari** [PortSwigger/turbo-intruder#18]
**Got this error while starting the trubo on ubuntu vm**

`root@ip-172-31-35-107:/home/ubuntu/tools# java -jar turbo-intruder-all.jar basic.py request.txt apiproxy-moviesv2.paytm.com:443 none
Please note that Turbo Intruder's SSL/TLS handling may differ slightly when run outside Burp Suite.
TURBO NOTICE: The input request appears to be using \n instead of \r\n as a line-ending. Consider changing your text-editor settings. Normalising...
ID | Word | Status | Wordcount | Length | Time
Starting attack...
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.python.core.PySystemState (file:/home/ubuntu/tools/turbo-intruder-all.jar) to method java.io.Console.encoding()
WARNING: Please consider reporting this to the maintainers of org.python.core.PySystemState
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Error launching attack - bad python?
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 2, in queueRequests
  File "<string>", line 58, in __init__
	at java.base/java.net.URL.<init>(URL.java:641)
	at java.base/java.net.URL.<init>(URL.java:530)
	at java.base/java.net.URL.<init>(URL.java:477)
	at burp.ThreadedRequestEngine.<init>(ThreadedRequestEngine.kt:22)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.python.core.PyReflectedConstructor.constructProxy(PyReflectedConstructor.java:211)

java.net.MalformedURLException: java.net.MalformedURLException: unknown protocol: apiproxy-moviesv2.paytm.com

	at org.python.core.Py.JavaError(Py.java:546)
	at org.python.core.Py.JavaError(Py.java:537)
	at org.python.core.PyReflectedConstructor.constructProxy(PyReflectedConstructor.java:221)
	at org.python.core.PyReflectedConstructor.__call__(PyReflectedConstructor.java:180)
	at org.python.core.PyObject.__call__(PyObject.java:419)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:223)
	at org.python.core.Deriveds.dispatch__init__(Deriveds.java:19)
	at org.python.core.PyObjectDerived.dispatch__init__(PyObjectDerived.java:1112)
	at org.python.core.PyType.type___call__(PyType.java:1713)
	at org.python.core.PyType.__call__(PyType.java:1696)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.PyObject.__call__(PyObject.java:435)
	at org.python.pycode._pyx0.__init__$9(<string>:67)
	at org.python.pycode._pyx0.call_function(<string>)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyFunction.__call__(PyFunction.java:476)
	at org.python.core.PyInstance.__init__(PyInstance.java:124)
	at org.python.core.PyClass.__call__(PyClass.java:193)
	at org.python.core.PyObject.__call__(PyObject.java:394)
	at org.python.pycode._pyx1.queueRequests$1(<string>:9)
	at org.python.pycode._pyx1.call_function(<string>)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:153)
	at org.python.core.PyFunction.__call__(PyFunction.java:423)
	at org.python.pycode._pyx2.f$0(<string>:1)
	at org.python.pycode._pyx2.call_function(<string>)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.core.Py.exec(Py.java:1430)
	at org.python.util.PythonInterpreter.exec(PythonInterpreter.java:267)
	at burp.Fast_httpKt.evalJython(fast-http.kt:134)
	at burp.Fast_httpKt.main(fast-http.kt:309)
Caused by: java.net.MalformedURLException: unknown protocol: apiproxy-moviesv2.paytm.com
	at java.base/java.net.URL.<init>(URL.java:641)
	at java.base/java.net.URL.<init>(URL.java:530)
	at java.base/java.net.URL.<init>(URL.java:477)
	at burp.ThreadedRequestEngine.<init>(ThreadedRequestEngine.kt:22)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.python.core.PyReflectedConstructor.constructProxy(PyReflectedConstructor.java:211)
	... 35 more

Error, check extender for full details: unknown protocol: apiproxy-moviesv2.paytm.com`

**Comment by albinowax** [comment]
This means the script you have supplied has failed to execute, so you need to fix it.
