### ISSUE TITLE
Turbo intruder sent no request

### ISSUE THREAD

**Issue by say2memohitverma** [PortSwigger/turbo-intruder#24]
can you help me with this issue?
this error show in the extender output:
There was an error executing your Python script. This is probably due to a flaw in your script, rather than a bug in Turbo Intruder :)
If you think it is a Turbo Intruder issue, try out this script: https://raw.githubusercontent.com/PortSwigger/turbo-intruder/master/resources/examples/debug.py
For your convenience, here's the full stack trace:
SyntaxError: ("mismatched input '' expecting DEDENT", ('<string>', 18, 2, '\t\tfor i in range(14):\n'))

	at org.python.core.ParserFacade.fixParseError(ParserFacade.java:95)
	at org.python.core.ParserFacade.parse(ParserFacade.java:205)
	at org.python.core.Py.compile_flags(Py.java:1976)
	at org.python.util.PythonInterpreter.exec(PythonInterpreter.java:267)
	at burp.Fast_httpKt.evalJython(fast-http.kt:133)
	at burp.TurboIntruderFrame$actionPerformed$1$1$1.invoke(fast-http.kt:264)
	at burp.TurboIntruderFrame$actionPerformed$1$1$1.invoke(fast-http.kt:188)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

Starting attack...
Cancelled attack
Starting attack...
Thread failed to connect
Thread failed to connect
Thread failed to connect
Thread failed to connect
Thread failed to connect
Thread failed to connect

**Comment by albinowax** [comment]
As the error message tells you, this is a problem with your Python script. Looks like you might be mixing tabs and spaces.
