### ISSUE TITLE
error starting attack 

### ISSUE THREAD

**Issue by bukyapavankumar** [PortSwigger/turbo-intruder#44]
output:

Loaded Turbo Intruder v1.0.18
Starting attack...
There was an error executing your Python script. This is probably due to a flaw in your script, rather than a bug in Turbo Intruder :)
If you think it is a Turbo Intruder issue, try out this script: https://raw.githubusercontent.com/PortSwigger/turbo-intruder/master/resources/examples/debug.py
For your convenience, here's the full stack trace:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 10, in queueRequests
  File "<string>", line 80, in queue
	at burp.RequestEngine.queue(RequestEngine.kt:83)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.base/java.lang.reflect.Method.invoke(Method.java:564)

java.lang.Exception: java.lang.Exception: The request has payloads specified, but no %s injection markers

	at org.python.core.Py.JavaError(Py.java:546)
	at org.python.core.Py.JavaError(Py.java:537)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:188)
	at org.python.core.PyObject.__call__(PyObject.java:419)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:218)
	at org.python.pycode._pyx0.queue$10(<string>:80)
	at org.python.pycode._pyx0.call_function(<string>)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.pycode._pyx1.queueRequests$1(<string>:13)
	at org.python.pycode._pyx1.call_function(<string>)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:153)
	at org.python.core.PyFunction.__call__(PyFunction.java:423)
	at org.python.pycode._pyx2.f$0(<string>:1)
	at org.python.pycode._pyx2.call_function(<string>)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.core.Py.exec(Py.java:1430)
	at org.python.util.PythonInterpreter.exec(PythonInterpreter.java:267)
	at burp.Fast_httpKt.evalJython(fast-http.kt:139)
	at burp.TurboIntruderFrame$actionPerformed$1$1$1.invoke(fast-http.kt:278)
	at burp.TurboIntruderFrame$actionPerformed$1$1$1.invoke(fast-http.kt:201)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
Caused by: java.lang.Exception: The request has payloads specified, but no %s injection markers
	at burp.RequestEngine.queue(RequestEngine.kt:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:186)
	... 28 more

Cancelled attack

**Comment by albinowax** [comment]
As the error states, this is due to a flaw in your script, rather than a bug in Turbo Intruder.

**Comment by bukyapavankumar** [comment]
i didnt change the code ,its the default

**Comment by bukyapavankumar** [comment]
> As the error states, this is due to a flaw in your script, rather than a bug in Turbo Intruder.

ye i think thats whe the error using debug.py it worked fine.
how do i add wordlist by code in it .i think i did it wrong. i need to specify a path to wordlist on my desktop on windows

**Comment by bukyapavankumar** [comment]
@albinowax it says payload specified but no %s markers.what do I need to do?

**Comment by albinowax** [comment]
Put %s in the request where you want your payload to go
