### ISSUE TITLE
win10 : User Python error , 'org.Python.core.Py.getSystemState()' return null

### ISSUE THREAD

**Issue by kejaly** [PortSwigger/turbo-intruder#69]
hello , i hava a error when i use turbo . 
and i just use the default.py and only change the dicPath , so it's may be not the flaw in the script .

my os is win10  ,and the burp verion is 2021.2 and when i use the burp 2020.2 ,it is the same error

![image](https://user-images.githubusercontent.com/46043605/110067706-3b259680-7daf-11eb-96d9-e27b42afc713.png)

the whole output is :

```
Loaded Turbo Intruder v1.1.4
Starting attack...
There was an error executing your Python script. This is probably due to a flaw in your script, rather than a bug in Turbo Intruder :)
If you think it is a Turbo Intruder issue, try out this script: https://raw.githubusercontent.com/PortSwigger/turbo-intruder/master/resources/examples/debug.py
For your convenience, here's the full stack trace:
java.lang.IllegalArgumentException: Cannot create PyString with non-byte value
	at org.python.core.PyString.<init>(PyString.java:64)
	at org.python.core.PyString.<init>(PyString.java:70)
	at org.python.core.Py.newString(Py.java:641)
	at org.python.core.PySystemState.initRegistry(PySystemState.java:800)
	at org.python.core.PySystemState.doInitialize(PySystemState.java:1045)
	at org.python.core.PySystemState.initialize(PySystemState.java:974)
	at org.python.core.PySystemState.initialize(PySystemState.java:930)
	at org.python.core.PySystemState.initialize(PySystemState.java:925)
	at org.python.core.PySystemState.initialize(PySystemState.java:920)
	at org.python.core.PySystemState.initialize(PySystemState.java:916)
	at org.python.core.ThreadStateMapping.getThreadState(ThreadStateMapping.java:32)
	at org.python.core.Py.getThreadState(Py.java:1440)
	at org.python.core.Py.getThreadState(Py.java:1436)
	at org.python.core.Py.getSystemState(Py.java:1456)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:105)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:94)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:71)
	at burp.Fast_httpKt.evalJython(fast-http.kt:139)
	at burp.TurboIntruderFrame$actionPerformed$1$4$1.invoke(fast-http.kt:415)
	at burp.TurboIntruderFrame$actionPerformed$1$4$1.invoke(fast-http.kt:218)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

Starting attack...
There was an error executing your Python script. This is probably due to a flaw in your script, rather than a bug in Turbo Intruder :)
If you think it is a Turbo Intruder issue, try out this script: https://raw.githubusercontent.com/PortSwigger/turbo-intruder/master/resources/examples/debug.py
For your convenience, here's the full stack trace:
java.lang.NullPointerException: Cannot read field "modules" because the return value of "org.python.core.Py.getSystemState()" is null
	at org.python.core.PyModule.module___init__(PyModule.java:64)
	at org.python.core.PyModule.<init>(PyModule.java:47)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:112)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:94)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:71)
	at burp.Fast_httpKt.evalJython(fast-http.kt:139)
	at burp.TurboIntruderFrame$actionPerformed$1$4$1.invoke(fast-http.kt:415)
	at burp.TurboIntruderFrame$actionPerformed$1$4$1.invoke(fast-http.kt:218)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)


```

**Comment by albinowax** [comment]
Can you try https://raw.githubusercontent.com/PortSwigger/turbo-intruder/master/resources/examples/debug.py

**Comment by kejaly** [comment]
it is the name error  
![image](https://user-images.githubusercontent.com/46043605/110930900-9eda3180-8364-11eb-826c-84c245106dcf.png)

**Comment by kejaly** [comment]
Could it be this reason ？
https://github.com/jython/frozen-mirror/issues/90
![image](https://user-images.githubusercontent.com/46043605/111021437-2ed0b780-8407-11eb-9cc9-b73228ea8f24.png)

**Comment by albinowax** [comment]
Unfortunately I can't easily help, because I can't replicate this on my system.

**Comment by robot183** [comment]
Hi,I meet  this question too, may  I ask  you have  solved  this  problem.  thanks

**Comment by IceSeclude** [comment]
I also meet this problem, which has not been solved until now

**Comment by albinowax** [comment]
Thanks for the information, I'll investigate. In the meantime, you might find that you can avoid this issue by using the Burp installer, instead of launching it via the jar. This will use Burp's bundled version of Java.

**Comment by albinowax** [comment]
I've dug into this, and it looks like an issue with Jython that is possibly caused by having a platform language configured that it doesn't like. Unfortunately this isn't something I can fix as it's a Jython issue. You may find the workaround at the end of this thread works for you:

https://forum.portswigger.net/thread/jython-2-7-2-error-via-burp-suite-extensions-01800d81
